services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_pass
      - POSTGRES_DB=todo_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./code/projeto-2/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
      - PGUSER=todo_user
      - PGPASSWORD=todo_pass
      - PGDATABASE=todo_db
      - PGPORT=5432
    depends_on:
      - db

volumes:
  pgdata:
