services:
  db:
    image: postgres:17
    env_file:
      - ./.env
    ports:
<<<<<<< HEAD
      - "5432:5432"
=======
      - "5444:5444"
>>>>>>> fbc79bc (adding projects done in the workshop)
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: projeto-3-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
<<<<<<< HEAD
      db:
        condition: service_started
=======
      - db
>>>>>>> fbc79bc (adding projects done in the workshop)
    restart: unless-stopped
    container_name: projeto-3-app

volumes:
<<<<<<< HEAD
  db-data:
=======
  db-data:
>>>>>>> fbc79bc (adding projects done in the workshop)
